# Generated by Django 4.0.10 on 2024-11-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='IMDb_URL',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='video_release_date',
        ),
        migrations.AlterField(
            model_name='movie',
            name='avg_rating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='count_rating',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
