# Generated by Django 4.0.10 on 2024-11-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
