# Generated by Django 4.0.10 on 2024-11-02 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_rating_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_id',
            new_name='id',
        ),
    ]
