# Generated by Django 4.0.10 on 2024-11-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_currentcity_user_dateofbirth_user_occupation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=255, null=True),
        ),
    ]
