# Generated by Django 4.0.10 on 2024-11-02 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_movie_id_movie_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='id',
            new_name='movie_id',
        ),
    ]
