# Generated by Django 4.0.10 on 2024-11-02 08:33

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_id_movie_movie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.movie_image_file_path),
        ),
    ]
