# Generated by Django 4.0.10 on 2024-11-24 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='revenue',
        ),
    ]
