# Generated by Django 4.0.10 on 2024-11-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
