# Generated by Django 4.0.10 on 2024-11-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_movie_link_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='avg_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='movie',
            name='count_rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
