name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Cập nhật lên phiên bản mới hơn

      - name: Login to Docker Hub
        uses: docker/login-action@v2  # Cập nhật lên phiên bản mới hơn
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run Tests
        run: docker-compose run --rm app sh -c "python manage.py test"

      - name: Lint Code
        run: docker-compose run --rm app sh -c "flake8"
